import { NewsItem, Asset } from './types';

export const MOCK_NEWS: NewsItem[] = [
  {
    id: '1',
    headline: 'Apple Beats Q4 Earnings Expectations with Record iPhone Sales',
    summary: 'Apple Inc. reported quarterly earnings that surpassed Wall Street estimates, driven by strong iPhone 16 demand and services revenue hitting an all-time high of $24.2B.',
    source: 'Bloomberg',
    publishedAt: '2025-03-08T09:15:00Z',
    assetSymbol: 'AAPL',
    assetName: 'Apple Inc.',
    category: 'stocks',
    sentiment: 'bullish',
    marketReaction: { priceBefore: 218.40, priceAfter: 224.80, change5m: 1.2, change30m: 2.4, change1h: 2.9, currency: '$' },
    tags: ['Bullish', 'Earnings', 'Breakout'],
    isBreaking: false,
  },
  {
    id: '2',
    headline: 'Bitcoin Surges Past $95,000 as Institutional Demand Accelerates',
    summary: 'BTC broke above the $95K resistance level amid news that a major sovereign wealth fund has allocated 2% of its portfolio to Bitcoin ETFs, fueling optimism about long-term adoption.',
    source: 'CoinDesk',
    publishedAt: '2025-03-08T08:42:00Z',
    assetSymbol: 'BTC',
    assetName: 'Bitcoin',
    category: 'crypto',
    sentiment: 'bullish',
    marketReaction: { priceBefore: 92100, priceAfter: 95400, change5m: 1.8, change30m: 3.3, change1h: 3.6, currency: '$' },
    tags: ['Bullish', 'Breakout', 'High Volatility'],
    isBreaking: true,
  },
  {
    id: '3',
    headline: 'Fed Signals Potential Rate Pause Amid Sticky Inflation Data',
    summary: 'Federal Reserve officials indicated they may hold interest rates steady at next month\'s meeting, citing persistent core inflation at 3.2%. Markets reacted with mild risk-off positioning.',
    source: 'Reuters',
    publishedAt: '2025-03-08T07:30:00Z',
    assetSymbol: 'USD',
    assetName: 'US Dollar',
    category: 'macro',
    sentiment: 'bearish',
    marketReaction: { priceBefore: 104.2, priceAfter: 103.8, change5m: -0.3, change30m: -0.5, change1h: -0.4, currency: '' },
    tags: ['Macro Event', 'Bearish'],
    isBreaking: false,
  },
  {
    id: '4',
    headline: 'Tesla Deliveries Miss Q1 Estimates, Stock Falls Pre-Market',
    summary: 'Tesla delivered 386,810 vehicles in Q1, falling short of analyst estimates of 430,000. The miss was attributed to factory retooling in Austin and weaker demand in Europe.',
    source: 'CNBC',
    publishedAt: '2025-03-08T06:55:00Z',
    assetSymbol: 'TSLA',
    assetName: 'Tesla Inc.',
    category: 'stocks',
    sentiment: 'bearish',
    marketReaction: { priceBefore: 245.60, priceAfter: 232.10, change5m: -2.8, change30m: -4.9, change1h: -5.5, currency: '$' },
    tags: ['Bearish', 'High Volatility', 'Earnings'],
    isBreaking: false,
  },
  {
    id: '5',
    headline: 'Gold Hits 3-Month High as Safe-Haven Demand Rises',
    summary: 'Spot gold climbed to $2,198/oz, the highest level in three months, as geopolitical tensions in Eastern Europe and a softer dollar prompted investors to seek safe-haven assets.',
    source: 'MarketWatch',
    publishedAt: '2025-03-08T06:10:00Z',
    assetSymbol: 'XAU',
    assetName: 'Gold',
    category: 'commodities',
    sentiment: 'bullish',
    marketReaction: { priceBefore: 2164, priceAfter: 2198, change5m: 0.4, change30m: 1.1, change1h: 1.6, currency: '$' },
    tags: ['Bullish', 'Macro Event'],
    isBreaking: false,
  },
  {
    id: '6',
    headline: 'Ethereum Upgrade EIP-7702 Goes Live, Gas Fees Drop 60%',
    summary: 'The Ethereum network successfully deployed its long-awaited account abstraction upgrade, cutting average gas fees from $8.40 to $3.20. On-chain activity surged 40% in the 24 hours following the upgrade.',
    source: 'The Block',
    publishedAt: '2025-03-08T05:20:00Z',
    assetSymbol: 'ETH',
    assetName: 'Ethereum',
    category: 'crypto',
    sentiment: 'bullish',
    marketReaction: { priceBefore: 3480, priceAfter: 3690, change5m: 2.1, change30m: 4.8, change1h: 6.0, currency: '$' },
    tags: ['Bullish', 'Breakout', 'High Volatility'],
    isBreaking: true,
  },
  {
    id: '7',
    headline: 'EUR/USD Drops to 3-Week Low on ECB Dovish Comments',
    summary: 'The Euro fell sharply against the US dollar after ECB President Lagarde hinted at potential rate cuts in June, citing slowing eurozone growth and easing wage pressures.',
    source: 'FX Street',
    publishedAt: '2025-03-08T04:45:00Z',
    assetSymbol: 'EURUSD',
    assetName: 'EUR/USD',
    category: 'forex',
    sentiment: 'bearish',
    marketReaction: { priceBefore: 1.0840, priceAfter: 1.0778, change5m: -0.4, change30m: -0.5, change1h: -0.6, currency: '' },
    tags: ['Bearish', 'Macro Event'],
    isBreaking: false,
  },
  {
    id: '8',
    headline: 'NVIDIA Data Center Revenue Tops $30B for First Time in Q4',
    summary: 'NVIDIA\'s data center segment generated $30.8B in Q4 revenue, driven by insatiable demand for H100 and Blackwell GPUs. Full-year revenue rose 122% to $130.5B.',
    source: 'Bloomberg',
    publishedAt: '2025-03-07T22:10:00Z',
    assetSymbol: 'NVDA',
    assetName: 'NVIDIA Corp.',
    category: 'stocks',
    sentiment: 'bullish',
    marketReaction: { priceBefore: 840.20, priceAfter: 878.50, change5m: 2.2, change30m: 3.8, change1h: 4.6, currency: '$' },
    tags: ['Bullish', 'Earnings', 'Breakout'],
    isBreaking: false,
  },
  {
    id: '9',
    headline: 'Oil Slides on OPEC+ Production Hike Reports',
    summary: 'Crude oil prices dropped below $80/barrel after reports emerged that several OPEC+ members are considering raising output limits by 500,000 bpd starting May, easing supply concerns.',
    source: 'Reuters',
    publishedAt: '2025-03-07T20:35:00Z',
    assetSymbol: 'OIL',
    assetName: 'Crude Oil',
    category: 'commodities',
    sentiment: 'bearish',
    marketReaction: { priceBefore: 82.40, priceAfter: 79.60, change5m: -1.1, change30m: -2.8, change1h: -3.4, currency: '$' },
    tags: ['Bearish', 'Macro Event'],
    isBreaking: false,
  },
  {
    id: '10',
    headline: 'SEC Approves First Spot Solana ETF Applications',
    summary: 'The SEC gave the green light to four spot Solana ETF applications, marking a major regulatory milestone for the altcoin market. SOL surged 18% on the news.',
    source: 'CoinTelegraph',
    publishedAt: '2025-03-07T18:00:00Z',
    assetSymbol: 'SOL',
    assetName: 'Solana',
    category: 'crypto',
    sentiment: 'bullish',
    marketReaction: { priceBefore: 142, priceAfter: 167, change5m: 5.2, change30m: 12.4, change1h: 17.6, currency: '$' },
    tags: ['Bullish', 'Regulation', 'Breakout', 'High Volatility'],
    isBreaking: true,
  },
  {
    id: '11',
    headline: 'Amazon Announces $5B Share Buyback Program',
    summary: 'Amazon\'s board authorized a new $5 billion share repurchase program, signaling confidence in long-term business performance following strong AWS growth guidance.',
    source: 'WSJ',
    publishedAt: '2025-03-07T16:20:00Z',
    assetSymbol: 'AMZN',
    assetName: 'Amazon.com',
    category: 'stocks',
    sentiment: 'bullish',
    marketReaction: { priceBefore: 196.30, priceAfter: 199.80, change5m: 0.8, change30m: 1.5, change1h: 1.8, currency: '$' },
    tags: ['Bullish'],
    isBreaking: false,
  },
  {
    id: '12',
    headline: 'Bank of Japan Hikes Rates for Second Time This Year',
    summary: 'The BoJ raised its benchmark rate to 0.5%, the highest in 17 years, citing progress toward its 2% inflation target. The Yen surged while Japanese equities slipped.',
    source: 'Nikkei',
    publishedAt: '2025-03-07T04:30:00Z',
    assetSymbol: 'USDJPY',
    assetName: 'USD/JPY',
    category: 'forex',
    sentiment: 'neutral',
    marketReaction: { priceBefore: 151.2, priceAfter: 149.4, change5m: -0.8, change30m: -1.0, change1h: -1.2, currency: '' },
    tags: ['Macro Event', 'High Volatility'],
    isBreaking: false,
  },
];

export const MOCK_ASSETS: Asset[] = [
  { symbol: 'AAPL', name: 'Apple Inc.', category: 'stocks', price: 224.80, change24h: 6.40, changePercent24h: 2.93, currency: '$' },
  { symbol: 'TSLA', name: 'Tesla Inc.', category: 'stocks', price: 232.10, change24h: -13.50, changePercent24h: -5.50, currency: '$' },
  { symbol: 'NVDA', name: 'NVIDIA Corp.', category: 'stocks', price: 878.50, change24h: 38.30, changePercent24h: 4.56, currency: '$' },
  { symbol: 'AMZN', name: 'Amazon.com', category: 'stocks', price: 199.80, change24h: 3.50, changePercent24h: 1.78, currency: '$' },
  { symbol: 'BTC', name: 'Bitcoin', category: 'crypto', price: 95400, change24h: 3300, changePercent24h: 3.59, currency: '$' },
  { symbol: 'ETH', name: 'Ethereum', category: 'crypto', price: 3690, change24h: 210, changePercent24h: 6.03, currency: '$' },
  { symbol: 'SOL', name: 'Solana', category: 'crypto', price: 167, change24h: 25, changePercent24h: 17.60, currency: '$' },
  { symbol: 'XAU', name: 'Gold', category: 'commodities', price: 2198, change24h: 34, changePercent24h: 1.57, currency: '$' },
  { symbol: 'OIL', name: 'Crude Oil', category: 'commodities', price: 79.60, change24h: -2.80, changePercent24h: -3.40, currency: '$' },
  { symbol: 'EURUSD', name: 'EUR/USD', category: 'forex', price: 1.0778, change24h: -0.0062, changePercent24h: -0.57, currency: '' },
  { symbol: 'USDJPY', name: 'USD/JPY', category: 'forex', price: 149.4, change24h: -1.8, changePercent24h: -1.19, currency: '' },
  { symbol: 'USD', name: 'US Dollar Index', category: 'macro', price: 103.8, change24h: -0.4, changePercent24h: -0.38, currency: '' },
];

export const CATEGORIES = [
  { key: 'stocks', label: 'Stocks', icon: 'trending-up' },
  { key: 'crypto', label: 'Crypto', icon: 'logo-bitcoin' },
  { key: 'commodities', label: 'Commodities', icon: 'cube-outline' },
  { key: 'forex', label: 'Forex', icon: 'swap-horizontal' },
  { key: 'macro', label: 'Macro', icon: 'globe-outline' },
] as const;
